### ***VetoreMatriz***

In [2]:
vetor = [2,4,5,6]

for i in vetor:
  print(i);

2
4
5
6


In [9]:
matriz = [[1,2,3],[4,5,6],[7,8,9]];


for i in matriz:
  print(i);

[1, 2, 3]
[4, 5, 6]
[7, 8, 9]


In [6]:
type(matriz);#list

In [10]:
import numpy as np

vetor2 = np.array([1,-3,4.2,5]); #vetor

print(vetor2);

[ 1.  -3.   4.2  5. ]


In [12]:
matriz2 = np.ones((2,3)); #matriz
print(matriz2);

[[1. 1. 1.]
 [1. 1. 1.]]


In [14]:
matriz3 = np.diag((2,3,6,8,10,69)) #diagonal
matriz3

array([[ 2,  0,  0,  0,  0,  0],
       [ 0,  3,  0,  0,  0,  0],
       [ 0,  0,  6,  0,  0,  0],
       [ 0,  0,  0,  8,  0,  0],
       [ 0,  0,  0,  0, 10,  0],
       [ 0,  0,  0,  0,  0, 69]])